#!/usr/bin/bash

OS_NAME=$(uname)
rm -rf .git
python -m venv venv/
if [[ "$OS_NAME" == "Linux" || "$OS_NAME" == "Darwin" ]]; then
  . venv/bin/activate
else
  . venv/Scripts/activate
fi
pip install -r requirements.txt
npm install
